altair-graphql/altair

- src/app/app.component.html
This PR fixes the issue with the set header's modal not closing when the save button is clicked
> toggle set header modal on save

- src/scss/components/_editor.scss
...
- Added a z-index of the query-result__bottom-actions div, set to 3 
- 
-
> Added Z-index for container to allow Download Link to be clickable

- src/app/actions/history/history.ts
- src/app/components/history-dialog/history-dialog.component.html
- src/app/components/history-dialog/history-dialog.component.ts
- src/app/containers/window/window.component.html
- src/app/containers/window/window.component.ts
- src/app/reducers/history/history.ts
- src/assets/i18n/default.json
#418 
- Adding a clear history button to the history dialog.
> clear history feature #418

- README.md
- docs/_config.yml
Update the `brew cask` installation command to use the correct name, `altair-graphql-client`. See https://github.com/Homebrew/homebrew-cask/blob/master/Casks/altair-graphql-client.rb.
- Update installation comand
> Fix brew cask install command

- packages/altair-express-middleware/index.ts
Sets the correct content-type for the javascript response in initial options
> Set correct header for js response

- package.json
> chore: pin ng-zorro-antd to 8.1.1

- README.md
The `CONTRIBUTING.md` was moved to `.github`  in change commit 96d7d1c271afce3d91b82f620d89e060ac5f7876 but the `README` wasn't updated
Correcting this to make life better for anyone going to the `README` in order to find that document
No issue 
- N/A
- Add correct path for `CONTRIBUTING.md`
> Update CONTRIBUTING.md link

- src/app/services/gql/gql.service.ts
When serializing params for GET-based GraphQL calls, `null` is cast to a string for at least `operationName`, which causes certain GraphQL libraries to have issues. Since query parameters for GET requests can't cleanly convey a null value, when serializing the parameters to perform a GET request, it makes sense to me to not include empty params at all.
- When sending GraphQL GET requests, only include params if they contain data, as the values are otherwise incorrectly cast to strings.
> Only add query params for GET requests if not empty

- src/app/config.ts
- src/app/reducers/environments.ts
- src/app/reducers/windows.ts
- Adds the ability to pass in `initialEnvironments` to AltairGraphQL.init()
Here's a sample config to test:
```js
document.addEventListener("DOMContentLoaded", () => {
AltairGraphQL.init({
initialEnvironments: {
base: {
title: "Base",
variables: {
"app-name": "altair-playground",
"app-version": "1.0.0"
}
},
subEnvironments: [
{
title: "Production",
variables: {
token: "ABC..."
}
},
{
title: "Staging",
variables: {
token: "XYZ..."
}
}
]
}
});
});
```
> Add support for setting initial environments

- packages/altair-electron/src/updates.js
Minor grammatical fix in 'Install Updates' message
- [❌] Ran `npm run test-build`
I did this but it failed for some reason in `graphql-linter`.
I'm assuming this is not related to my very small change!
- Minor grammatical fix in 'Install Updates' message
> Minor grammatical fix in 'Install Updates' message

- .github/PULL_REQUEST_TEMPLATE.md
Update PR template to use `yarn` instead of `npm`
To help prevent people like me using `npm install` instead of `yarn install` 😄 https://github.com/imolorhe/altair/pull/1140#issuecomment-569537366
- [✔] Ran `yarn run test-build`
- Update PR template to use `yarn` instead of `npm`
> Update PR template to use yarn instead of npm

- docs/docs/integrations/altair-express-middleware.md
- docs/docs/integrations/altair-koa-middleware.md
- docs/docs/integrations/altair-static.md
- docs/docs/integrations/gatsby-plugin-altair-graphql.md
The Koa docs incorrectly said the option was `endpoint` instead of `endpointURL`.
I also tidied up some of the surrounding grammar and formatting.
- Updated Koa docs.
> Fix the Koa docs for endpointURL

- packages/altair-static/src/__snapshots__/index.test.ts.snap
- packages/altair-static/src/index.test.ts
- packages/altair-static/src/index.ts
This fixes an issue with how **altair-static** rendered stringified JSON objects. It was incorrectly rendering JSON objects by surrounding the stringified object with template string quotes (\` ... \`):
> Expected: `initialHeaders: {\\"X-GraphQL-Token\\":\\"asd7-237s-2bdk-nsdk4\\"},`
> Actual ``initialHeaders: `{\\"X-GraphQL-Token\\":\\"asd7-237s-2bdk-nsdk4\\"}`,`` (notice unwanted backticks)
In addition to the above fix, this PR also includes the `initialSettings` in the rendering which was previously missing.
- Fix **altair-static** JSON object rendering for injected script tag.
- Add `initialSettings` option to init options in **altair-static**.
> Correct object handling in altair-static render function

- docs/docs/features/settings-pane.md
- packages/altair-app/src/app/store/settings/settings.reducer.ts
- packages/altair-app/src/app/utils/settings.schema.json
- packages/altair-app/src/app/utils/validate_settings_schema.js
This is a very small change. When I used this for the first time I noticed that all settings descriptions ended in a period except for one. So this PR removes the period from the one that has it.
Before
After
- Change settings description text
> Fix small text inconsistency in the settings panel

- packages/altair-app/src/app/app.module.ts
- packages/altair-app/src/app/effects/query.spec.ts
- packages/altair-app/src/app/effects/query.ts
- packages/altair-app/src/app/services/gql/gql.service.ts
- packages/altair-app/src/app/services/index.ts
- packages/altair-app/src/app/services/subscriptions/providers/ws.ts
- packages/altair-app/src/app/services/subscriptions/subscription-factory.service.ts
- packages/altair-app/src/app/services/subscriptions/subscription-provider.ts
This creates a new layer of abstraction for subscriptions. This layer of abstraction would enable the adding of more subscription implementations like the AWS Appsync implementation, or even Action cable.
> Added subscription provider abstraction

- docs/docs/index.md
Calling `brew cask install` is disabled.
Same as #1412 .
This is not relevant since this PR is simply a document change.
> Fix installation instructions

- docs/docs/features/graphql-subscriptions.md
- packages/altair-app/src/app/services/subscriptions/providers/app-sync.ts
#1432 - Add the Amazon Cognito user pools and OpenID Connect support for AWS AppSync Subscription
- Add the aws_appsync_jwtToken support
- Allow setting aws_appsync_apiKey conditionally
- Update the code to use appSync 3+ style (https://github.com/awslabs/aws-mobile-appsync-sdk-js#using-authorization-and-subscription-links-with-apollo-client-no-offline-support)
> Add the Amazon Cognito user pools and OpenID Connect support for AWS AppSync Subscription

- packages/altair-app/src/app/components/components.module.ts
- packages/altair-app/src/app/components/fancy-input-marker/fancy-input-marker.component.html
- packages/altair-app/src/app/components/fancy-input-marker/fancy-input-marker.component.spec.ts
- packages/altair-app/src/app/components/fancy-input-marker/fancy-input-marker.component.ts
- packages/altair-app/src/app/components/fancy-input/__snapshots__/fancy-input.component.spec.ts.snap
- packages/altair-app/src/app/components/fancy-input/fancy-input.component.html
- packages/altair-app/src/app/components/fancy-input/fancy-input.component.spec.ts
- packages/altair-app/src/app/components/fancy-input/fancy-input.component.ts
- packages/altair-app/src/scss/components/_fancy-input.scss
Made it smarter.
Added tooltip showing resolved value.
Closes #1463.
> Updated fancy input

- .changeset/shiny-bobcats-attack.md
- README.md
- packages/altair-app/src/app/modules/altair/config.ts
- packages/altair-app/src/app/modules/altair/services/subscriptions/subscription-provider-registry.service.ts
- packages/altair-app/src/app/modules/altair/store/query/query.reducer.ts
- packages/altair-static/src/__snapshots__/index.test.ts.snap
- packages/altair-static/src/index.ts
If there is any documentation to be updated for this, I will do it, I've been using altair all this time just with type definitions.
Add the possibility of setting the initial config for the subscriptions provider, since with the new graphql-ws integration, in some new projects I'm working on, graphql-ws is going to be the default.
> add initialSubscriptionsProvider config

- packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-type/doc-viewer-type.component.html
- packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-type/doc-viewer-type.component.ts
The the docviewer type was not included in https://github.com/altair-graphql/altair/commit/c9376c35f8490bd3a458f5f2a6bfde729c7f7014
> fix default values in doc viewer type.

- packages/altair-app/src/app/modules/altair/utils/index.spec.ts
- packages/altair-app/src/app/modules/altair/utils/index.ts
https://github.com/altair-graphql/altair/issues/1735
Added a regex to test if given string is an environment variable. If so - pass it as is, thus fixing the mentioned issue.
> add variable checker to full url checker

- packages/altair-app/src/app/modules/altair/services/electron-app/electron-app.service.ts
- packages/altair-app/src/app/modules/altair/services/notify/notify.service.ts
- packages/altair-app/src/app/modules/altair/utils/settings.schema.json
- packages/altair-app/src/app/modules/altair/utils/validate_settings_schema.js
- packages/altair-core/src/types/state/settings.interfaces.ts
- packages/altair-electron/src/app/actions.js
- packages/altair-electron/src/app/menu.js
- packages/altair-electron/src/app/window.js
- packages/altair-electron/src/settings/main/events.js
- packages/altair-electron/src/updates.js
#1612
- Replaces the "Update available" window with a notification pop up 
- Adds a setting to disable the "Update available" notification
> Add setting to disable the update available notification (#1)

- .github/CONTRIBUTING.md
- [ x] Ran `yarn test-build`
- [ y] Updated relevant documentations
- [x ] Updated matching config options in altair-static
Updating egghead course url. existing url provided in documentation is returning 404 page not found error. 
refer to the screenshot below.
> Update egghead course url

- packages/altair-fastify-plugin/src/index.ts
Support content security policy that forbids inline scripts.
Added get endpoint to render `initial_options.js` when `serveInitialOptionsInSeperateRequest` is set to `true`
> feat: support csp for fastify plugin

- packages/altair-fastify-plugin/package.json
- packages/altair-fastify-plugin/src/index.ts
- packages/altair-fastify-plugin/yarn.lock
update deprecated fastify-static dependency to @fastify/static as described in the issue
> fix(deps): update deprecated fastify-static dependency

- packages/altair-electron/src/app/window.js
[Bug: Local plugins get rejected by Content-Security-Policy](https://github.com/altair-graphql/altair/issues/1888)
Adds allowed source to Script src for plugins that are loaded from a local folder through "file://[...]"
> Add new scriptSrc for local files

- README.md
No issue raised, but I note that AppGet no longer exists, thus may be removed from the install instructions. It still works with Chocolatey though.
N/A
Only a change to the Readme
> AppGet no longer exists 😢

- packages/altair-app/src/app/modules/altair/components/subscription-url-dialog/subscription-url-dialog.component.spec.ts
Part of #1717
This PR adds tests around the functionality of the `subscription-url-dialog.component`:
- handleEditorRefresh gets called on change detection
- subscriptionUrlChange
- updateSubscriptionProviderId
> Add tests to subscription-url-dialog.component

- packages/altair-app/e2e/tsconfig.e2e.json
- packages/altair-app/src/app/modules/altair/altair.module.ts
- packages/altair-app/src/app/modules/altair/components/edit-collection-dialog/__snapshots__/edit-collection-dialog.component.spec.ts.snap
- packages/altair-app/src/app/modules/altair/components/edit-collection-dialog/edit-collection-dialog.component.html
- packages/altair-app/src/app/modules/altair/components/edit-collection-dialog/edit-collection-dialog.component.spec.ts
- packages/altair-app/src/app/modules/altair/components/edit-collection-dialog/edit-collection-dialog.component.ts
- packages/altair-app/src/app/modules/altair/components/settings-dialog/settings-dialog.component.spec.ts
- packages/altair-app/src/app/modules/altair/containers/window/window.component.ts
- packages/altair-app/src/app/modules/altair/effects/query-collection.effect.ts
- packages/altair-app/src/app/modules/altair/effects/query.effect.spec.ts
- packages/altair-app/src/app/modules/altair/effects/query.effect.ts
- packages/altair-app/src/app/modules/altair/services/electron-app/electron-app.service.spec.ts
- packages/altair-app/src/app/modules/altair/services/environment/environment.service.ts
- packages/altair-app/src/app/modules/altair/services/index.ts
- packages/altair-app/src/app/modules/altair/services/keybinder/keybinder.service.spec.ts
- packages/altair-app/src/app/modules/altair/services/pre-request/pre-request.service.ts
- packages/altair-app/src/app/modules/altair/services/query-collection/query-collection.service.ts
- packages/altair-app/src/app/modules/altair/services/query/query.service.spec.ts
- packages/altair-app/src/app/modules/altair/services/query/query.service.ts
- packages/altair-app/src/app/modules/altair/services/window.service.spec.ts
- packages/altair-app/src/app/modules/altair/services/window.service.ts
- packages/altair-core/src/types/state/collection.interfaces.ts
The order of execution now is:
- collection pre request script
- (parent collections' pre request scripts)
- query pre request script
- send request/get response
- collection post request script
- (parent collections' post request scripts)
- query post request script
Created query service to contain complex query-related logic.
Closes #1763
> Added pre- and post-request scripts to collections

- packages/altair-app/e2e/tsconfig.e2e.json
- packages/altair-app/src/app/modules/altair/altair.module.ts
- packages/altair-app/src/app/modules/altair/components/edit-collection-dialog/__snapshots__/edit-collection-dialog.component.spec.ts.snap
- packages/altair-app/src/app/modules/altair/components/edit-collection-dialog/edit-collection-dialog.component.html
- packages/altair-app/src/app/modules/altair/components/edit-collection-dialog/edit-collection-dialog.component.spec.ts
- packages/altair-app/src/app/modules/altair/components/edit-collection-dialog/edit-collection-dialog.component.ts
- packages/altair-app/src/app/modules/altair/components/settings-dialog/settings-dialog.component.spec.ts
- packages/altair-app/src/app/modules/altair/containers/window/window.component.ts
- packages/altair-app/src/app/modules/altair/effects/query-collection.effect.ts
- packages/altair-app/src/app/modules/altair/effects/query.effect.spec.ts
- packages/altair-app/src/app/modules/altair/effects/query.effect.ts
- packages/altair-app/src/app/modules/altair/services/electron-app/electron-app.service.spec.ts
- packages/altair-app/src/app/modules/altair/services/environment/environment.service.ts
- packages/altair-app/src/app/modules/altair/services/index.ts
- packages/altair-app/src/app/modules/altair/services/keybinder/keybinder.service.spec.ts
- packages/altair-app/src/app/modules/altair/services/pre-request/pre-request.service.ts
- packages/altair-app/src/app/modules/altair/services/query-collection/query-collection.service.ts
- packages/altair-app/src/app/modules/altair/services/query/query.service.spec.ts
- packages/altair-app/src/app/modules/altair/services/query/query.service.ts
- packages/altair-app/src/app/modules/altair/services/window.service.spec.ts
- packages/altair-app/src/app/modules/altair/services/window.service.ts
- packages/altair-app/src/app/modules/altair/store/query/query.reducer.ts
- packages/altair-app/src/app/modules/altair/utils/index.spec.ts
- packages/altair-app/src/app/modules/altair/utils/index.ts
- packages/altair-core/src/config.ts
- packages/altair-core/src/types/state/collection.interfaces.ts
- packages/altair-static/src/index.ts
Allow relative subscription endpoint
Closes #1913
> Allow relative subscription endpoint

- packages/altair-fastify-plugin/example/mercurius.js
- packages/altair-fastify-plugin/example/mercurius.ts
- packages/altair-fastify-plugin/package.json
- packages/altair-fastify-plugin/yarn.lock
Fix compatibility issues with fastify v4
- Update @fastify/static because fastify v4
- Update mercurius to v10 because fastify v4
- Update fastify to v4 to use in examples
> fix(altair-fastify-plugin)(deps): update @fastify-static to support with fastify v4

- packages/altair-electron/src/settings/renderer/app.js
Currently, there is a bug where it is impossible to set the proxy settings via the `Desktop Settings` menu. This is because `initialData` start as `undefined`, thus causing `Object.keys()` to throw an error and the rest of the initializer function never runs. This means that none of the save & submit functionality works because it never gets setup properly.
To fix this, you can just default `initialData` to an empty object.
> Fix proxy settings issue

- packages/altair-app/src/app/modules/altair/components/query-editor/gql-extensions.ts
set noop command for Ctrl-Enter
Closes #2015
>  set noop command for Ctrl-Enter

- packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.ts
- packages/altair-app/src/app/modules/altair/services/environment/environment.service.ts
- packages/altair-app/src/app/modules/altair/utils/index.ts
Update the schema of the new editor when the beta flag is changed Added extra checks for header value before hydrating Added extra check for electron when opening external URL
#2020 
#2021 
#2022
> Minor fixes

- DEV.md
- packages/altair-app/src/app/modules/altair/components/query-editor/__snapshots__/query-editor.component.spec.ts.snap
- packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.html
- packages/altair-app/src/app/modules/altair/components/query-result/query-result.component.html
- packages/altair-app/src/app/modules/altair/components/query-result/query-result.component.ts
- packages/altair-app/src/app/modules/altair/containers/window/window.component.html
- packages/altair-app/src/app/modules/altair/containers/window/window.component.ts
- packages/altair-app/src/app/modules/altair/effects/query.effect.ts
- packages/altair-app/src/app/modules/altair/services/pre-request/errors.ts
- packages/altair-app/src/app/modules/altair/services/pre-request/pre-request.service.ts
- packages/altair-app/src/app/modules/altair/store/query/query.action.ts
- packages/altair-app/src/app/modules/altair/store/query/query.reducer.ts
- packages/altair-app/src/app/modules/altair/store/query/selectors.ts
- packages/altair-app/src/assets/i18n/default.json
- packages/altair-app/src/index.html
- packages/altair-app/src/scss/components/_editor.scss
- packages/altair-app/src/scss/components/_request-script-editor.scss
- packages/altair-app/src/scss/components/_tabs.scss
- packages/altair-core/src/types/state/query.interfaces.ts
> Added request script logs

- packages/firebase-functions/src/index.ts
- packages/firebase-functions/src/onDeleteTrigger.ts
added function to delete queries when deleting collections
> added function to delete queries when deleting collections

- packages/altair-app/src/app/modules/altair/services/window.service.ts
> Toggle variable pane on window import

- DEV.md
- packages/altair-app/src/app/modules/altair/effects/query-collection.effect.ts
dispatch set collections before reloading
Closes #2193
> fix reload collection windows to set collection

- packages/altair-app/package.json
- packages/altair-app/src/app/modules/altair/utils/invariant.ts
- packages/altair-app/src/app/modules/altair/utils/issue/index.ts
- packages/altair-app/src/app/modules/altair/utils/issue/template.ts
Added new issue URL logic. Closes #2216
> added invariant util

- packages/altair-api/custom-matchers.ts
- packages/altair-api/jest.config.js
- packages/altair-api/jest.d.ts
- packages/altair-api/src/auth/mocks/prisma-service.mock.ts
- packages/altair-api/src/auth/mocks/stripe-service.mock.ts
- packages/altair-api/src/auth/user/user.service.spec.ts
Added unit tests for all public method of altair-api/UserService that is not a proxy call.
Along with that, I added a couple of mocks and custom matches to make the test cases more readable.
> Add unit tests for API user service

- packages/altair-api/jest.config.js
- packages/altair-api/src/auth/auth.controller.ts
- packages/altair-api/src/auth/auth.service.spec.ts
- packages/altair-api/src/auth/auth.service.ts
#1717
Added unit tests for all public method of altair-api/AuthService that is not a proxy call.
Change the Altair API jest config to only measure coverage for the source folder and ignore data holder files (DTO, input, module, strategy) and configs.
> Auth service unit tests

- packages/altair-api/custom-matchers.ts
- packages/altair-api/jest.config.js
- packages/altair-api/jest.d.ts
- packages/altair-api/src/auth/auth.controller.spec.ts
- packages/altair-api/src/auth/mocks/express.mock.ts
- packages/altair-api/src/auth/mocks/password.mock.ts
- packages/altair-api/src/auth/mocks/prisma-service.mock.ts
- packages/altair-api/src/auth/mocks/stripe-service.mock.ts
- packages/altair-api/src/auth/password/password.service.spec.ts
- packages/altair-api/src/auth/user/user.controller.spec.ts
- packages/altair-api/src/auth/user/user.service.spec.ts
#1717 
Added unit tests for all public methods of:
- AuthController
- PasswordService
- UserController
- UserService
Add dynamic mocks for Express request and response.
Add custom matches for user controller responses.
> Add remainder auth tests

- packages/altair-app/jest.config.js
- packages/altair-app/package.json
- packages/altair-app/src/app/modules/altair/services/electron-app/electron-app.service.ts
- packages/altair-electron/package.json
- packages/altair-electron/src/index.ts
- site/src/docs/features/prerequest-scripts.md
- yarn.lock
> Added electron crash reporter using sentry

- packages/altair-koa-middleware/package.json
Following [this conversation](https://github.com/altair-graphql/altair/pull/2342/files#r1416581529), will create a patch fix and move koa-send from peer dependency in a latter v6 update.
cc @jaydenseric
> fix koa middleware dependencies

- packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.ts
- packages/altair-app/src/app/modules/altair/services/gql/__snapshots__/fillFields.spec.ts.snap
- packages/altair-app/src/app/modules/altair/services/gql/fillFields.spec.ts
- packages/altair-app/src/app/modules/altair/services/gql/fillFields.ts
- packages/altair-app/src/app/modules/altair/services/gql/test-helper.ts
- yarn.lock
We recently updated cm6-graphql and graphql-language-service packages. The upgrade of graphql-language-service introduced a regression to the fillAllFields logic. Narrowed it down to [this change](https://github.com/graphql/graphiql/pull/3149).
For now I'm ignoring the token from cm6-graphql and generating it here until we fix it upstream in cm6-graphql.
#2349
> fix fill all fields regression

- cwex.yml
Mozilla ignores the CSP of the extension if it contains `unsafe-inline`, and it doesn't show any warnings either making this difficult to spot. I've verified that the pre request script still works without `unsafe-inline`.
#2358
> Removed unsafe-inline from extension CSP

- packages/altair-app/src/app/modules/altair/effects/query.effect.ts
- packages/altair-app/src/app/modules/altair/services/gql/gql.service.spec.ts
- packages/altair-app/src/app/modules/altair/services/gql/gql.service.ts
> updated to make multiple HTTP requests simultaneously

- packages/altair-app/angular.json
- packages/altair-app/jest.config.js
- packages/altair-app/package.json
- packages/altair-app/src/app/modules/altair/components/add-collection-query-dialog/__snapshots__/add-collection-query-dialog.component.spec.ts.snap
- packages/altair-app/src/app/modules/altair/components/schema-form/schema-form/schema-form.component.html
- packages/altair-app/src/app/modules/altair/directives/theme/theme.directive.spec.ts
- packages/altair-app/src/app/modules/altair/directives/theme/theme.directive.ts
- packages/altair-app/src/app/modules/altair/modules/shared/shared.module.ts
- packages/altair-app/src/scss/_ant-overrides.scss
- packages/altair-app/src/scss/components/_ui-form.scss
- packages/altair-app/src/styles.scss
- yarn.lock
> updated ng-zorro-antd

- packages/altair-app/src/app/modules/altair/components/action-bar/__snapshots__/action-bar.component.spec.ts.snap
- packages/altair-app/src/app/modules/altair/components/action-bar/action-bar.component.html
- packages/altair-app/src/app/modules/altair/components/action-bar/action-bar.component.spec.ts
This PR helps fix issue #1717 which is an ongoing issue that requests more tests for components in altair-app.
Checks
Ran yarn test-build
Updated relevant documentations
Updated matching config options in altair-static
I added tests for the event_emitters for the action_bar component to make sure they go off properly.
> event emitters tests in action_bar component

- packages/altair-app/src/app/modules/altair/components/codemirror/codemirror.component.ts
- packages/altair-app/src/app/modules/altair/components/query-editor/gql-extensions.ts
- packages/altair-app/src/app/modules/altair/components/variables-editor/utils.ts
- packages/altair-app/src/app/modules/altair/components/variables-editor/variables-editor.component.ts
- packages/altair-app/src/app/modules/altair/effects/query.effect.ts
- packages/altair-app/src/app/modules/altair/services/keybinder/keybinder.service.ts
- packages/altair-app/src/app/modules/altair/store/variables/variables.action.ts
> Added functionality to prettify variables

- packages/altair-app/src/app/modules/altair/components/post-request-editor/post-request-editor.component.ts
- packages/altair-app/src/app/modules/altair/components/pre-request-editor/pre-request-editor.component.ts
- packages/altair-app/src/app/modules/altair/services/pre-request/helpers.ts
- packages/altair-app/src/app/modules/altair/services/pre-request/pre-request.service.spec.ts
- packages/altair-app/src/app/modules/altair/services/query/query.service.ts
- packages/altair-docs/docs/features/prerequest-scripts.md
https://github.com/altair-graphql/altair/issues/2463
This change adds `operationName` string field to the `ScriptContextData` object. The value is populated from the global state (`state.query.selectedOperation`). 
This value is then available through `altair.data` helper object in pre/post-request context.
Docs have been updated to mention the newly available field.
> Add operationName to ScriptContextData

- packages/altair-api/src/app-bootstrap.ts
- packages/altair-api/src/auth/auth.service.spec.ts
- packages/altair-api/src/auth/auth.service.ts
- packages/altair-api/src/auth/mocks/stripe-service.mock.ts
- packages/altair-api/src/auth/models/change-password.input.ts
- packages/altair-api/src/auth/models/login.input.ts
- packages/altair-api/src/auth/models/refresh-token.input.ts
- packages/altair-api/src/auth/models/signup.input.ts
- packages/altair-api/src/auth/user/user.service.spec.ts
- packages/altair-api/src/auth/user/user.service.ts
- packages/altair-api/src/common/where-clauses.ts
- packages/altair-api/src/exceptions/invalid-request.exception.ts
- packages/altair-api/src/main.ts
- packages/altair-api/src/queries/queries.service.ts
- packages/altair-api/src/query-collections/query-collections.service.ts
- packages/altair-api/src/stripe-webhook/stripe-webhook.controller.ts
- packages/altair-api/src/stripe/stripe.service.ts
- packages/altair-api/src/team-memberships/team-memberships.service.ts
- packages/altair-api/src/teams/teams.service.ts
- packages/altair-api/src/workspaces/dto/create-workspace.dto.ts
- packages/altair-api/src/workspaces/workspaces.controller.ts
- packages/altair-api/src/workspaces/workspaces.service.ts
- packages/altair-api/tsconfig.json
- packages/altair-app/src/app/modules/altair/components/teams-dialog/teams-dialog.component.ts
- packages/altair-db/prisma/schema.prisma
> allow team members to create queries

- packages/altair-app/src/app/modules/altair/components/teams-dialog/teams-dialog.component.spec.ts
- packages/altair-app/src/app/modules/altair/components/teams-dialog/teams-dialog.component.ts
- packages/altair-app/src/app/modules/altair/effects/account.effect.ts
- packages/altair-app/src/app/modules/altair/effects/query-collection.effect.ts
- packages/altair-app/src/app/modules/altair/services/notify/notify.service.ts
- packages/altair-app/src/app/modules/altair/utils/errors.ts
- packages/altair-db/src/seed.ts
- packages/altair-docs/.vitepress/theme/components/Downloads.vue
- packages/altair-docs/updated.md
> recommend pro plan when limit is reached

- packages/altair-app/src/app/modules/altair/containers/altair/altair.component.html
- packages/altair-app/src/app/modules/altair/services/donation.service.ts
- packages/altair-docs/.vitepress/plugins/github-metadata.data.ts
- packages/altair-docs/updated.md
> stop showing donation alert for pro users

- packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-field/doc-viewer-field.component.html
- packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-field/doc-viewer-field.component.ts
- packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-type/doc-viewer-type.component.html
- packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-type/doc-viewer-type.component.ts
- packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer/doc-viewer.component.html
- packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer/doc-viewer.component.ts
- packages/altair-app/src/app/modules/altair/containers/window/window.component.html
- packages/altair-app/src/app/modules/altair/containers/window/window.component.ts
- packages/altair-core/src/types/state/settings.interfaces.ts
[#2220 ](https://github.com/altair-graphql/altair/issues/2220)
Adds a toggle button in settings to hide deprecated doc items
When the toggle button is disabled, the deprecated items should be visible
When the toggle button is enabled, the deprecated item should be hidden.
> feat: hide deprecated doc items (queries, mutations, fields...)

- packages/altair-app/src/app/modules/altair/services/gql/gql.service.spec.ts
- packages/altair-app/src/app/modules/altair/services/gql/gql.service.ts
- packages/altair-core/src/request/handlers/http.spec.ts
- packages/altair-docs/docs/features/file-upload.md
Support `$$` as a placeholder for the file index in multiple file mode for easier usage with nested file inputs.
#2459
> support placeholder in file variable name

- packages/altair-koa-middleware/package.json
> allow koa/router peer dependency > 11
