chrome-ext-files/manifest.json
package.json
src/app/components/doc-viewer/doc-viewer-field/doc-viewer-field.component.html
src/app/components/doc-viewer/doc-viewer-field/doc-viewer-field.component.ts
src/app/components/doc-viewer/doc-viewer-type/doc-viewer-type.component.html
src/app/components/doc-viewer/doc-viewer/doc-viewer.component.html
src/app/services/gql.service.ts

Fixed bugs in extension.

---

src/app/actions/windows/windows.ts
src/app/components/set-variable-dialog/set-variable-dialog.component.html
src/app/components/window-switcher/window-switcher.component.html
src/app/containers/app/app.component.scss
src/app/containers/window/window.component.html
src/app/reducers/windows.ts
src/app/services/window.service.ts
src/scss/_helpers.scss

Added better default window titles.

Added animations to dialogs and loader.

---

src/app/actions/query/query.ts
src/app/containers/window/window.component.html
src/app/containers/window/window.component.ts
src/app/effects/query.ts
src/scss/_buttons.scss

Added button to cancel query request on loading screen.

---

src/app/actions/query/query.ts
src/app/components/query-result/query-result.component.html
src/app/components/query-result/query-result.component.ts
src/app/containers/app/app.component.scss
src/app/containers/window/window.component.html
src/app/containers/window/window.component.ts
src/app/effects/query.ts
src/app/reducers/query/query.ts
src/app/services/gql.service.ts

Added logic to display response status code and time spent

---

package.json
src/app/app.module.ts
src/app/containers/window/window.component.ts
src/app/reducers/index.ts

Added ngrx-store-localstorage to improve syncing.

---

src/app/components/doc-viewer/doc-viewer-type/doc-viewer-type.component.html
src/app/components/doc-viewer/doc-viewer/doc-viewer.component.scss

Added template and styling for deprecation information.

---

src/app/actions/layout/layout.ts
src/app/components/window-switcher/window-switcher.component.html
src/app/components/window-switcher/window-switcher.component.ts
src/app/containers/app/app.component.html
src/app/containers/app/app.component.scss
src/app/containers/app/app.component.ts
src/app/reducers/layout/layout.ts
src/app/reducers/windows.ts
src/scss/_reset.scss

Added styles for editable window title.
Closes #66

Made window title editable on double click.

---

src/app/components/query-result/query-result.component.html
src/app/containers/app/app.component.scss

Changed no response content to blueprint content

---

src/app/actions/variables/variables.ts
src/app/components/set-variable-dialog/set-variable-dialog.component.html
src/app/components/set-variable-dialog/set-variable-dialog.component.spec.ts
src/app/components/set-variable-dialog/set-variable-dialog.component.ts
src/app/containers/app/app.component.scss
src/app/containers/window/window.component.html
src/app/containers/window/window.component.ts
src/app/effects/query.ts
src/app/reducers/variables/variables.ts
src/app/services/gql.service.ts
src/scss/_editor.scss

Changed variables input implementation to an editor.

---

chrome-ext-files/manifest.json
package.json
src/app/containers/app/app.component.ts

Fixed minor bug for first time users.

---

bin/update_version.sh
chrome-ext-files/manifest.json
package.json

Updated update_version script.

Updated app to 1.3.5

---

README.md
electron/main.js

Added shield badges in README file.

---

README.md
docs/_config.yml

Remove the web app links -- for now.

---

src/app/config.ts
src/app/containers/app/app.component.ts

- Auto detection of clients language
- Default language if detected is not available
- Language settings are now in config.ts (default language and available languages)

Auto-detection of client language

---

.travis.yml
src/app/effects/query.ts

Staging to master

---

.travis.yml

Added missing then in travis config file.

---

docs/_includes/landingfooter.html

Updated docs to pick first asset that matches where_exp.

---

docs/_config.yml

Updated unique term in docs.

---

src/assets/i18n/fr.json

Just a JSON file with the French text :)

Create French Translation

---

src/app/config.ts
src/assets/i18n/es.json

i18n - Add es.json (Spanish)

---

src/app/components/query-editor/query-editor.component.ts

...
- add toggle comment feature.
- key binding is the same as most IDE/text-editor, `cmd/ctrl + /`.
- this matches what `graphiql` provides.

add toggle command feature

---

.travis.yml
README.md
package.json
yarn.lock

Update to node 10 in .travis.yml

---

package.json

fix(package): update ng2-completer to version 2.0.8

---

src/app/containers/window/window.component.ts

...
- Removed graphql from window.component.ts
- 
-

Removed graphql from window.component.ts

---

README.md

As discussed in #874
#874
- [  ] Ran `npm run test-build`
- Added arch linux AUR Package to README

Added arch linux AUR Package to README

---

.github/opencollective.yml
packages/altair-electron/__tests__/index.test.js
packages/altair-electron/src/window.js
packages/altair-electron/yarn.lock

Added electron integration tests.

Added more electron integration tests.

---

packages/altair-app/src/scss/components/_query-collections.scss

Changed max height of query collections content wrapper to 9999em.

---

packages/altair-app/src/app/components/query-result/query-result.component.html
packages/altair-app/src/app/components/query-result/query-result.component.ts
packages/altair-app/src/app/containers/window/window.component.html
packages/altair-app/src/app/containers/window/window.component.ts
packages/altair-app/src/app/services/plugin/plugin-utils.ts
packages/altair-app/src/app/services/plugin/plugin.ts
packages/altair-app/src/main.ts

This provides the structural functionality required for implementing a plugin for #1204.

Added action button plugin type.

---

README.md
docs/docs/plugins/index.md
docs/docs/plugins/writing-plugin.md

Added initial plugins docs.

---

docs/docs/plugins/writing-plugin.md

Added docs for header and action button plugins

---

packages/altair-app/src/app/services/plugin/plugin-props-factory.ts
packages/altair-app/src/app/services/plugin/plugin.ts

...
- Add queryResponse to available plugin props

Add queryResponse to available plugin props

---

packages/altair-electron/src/app/actions.js
packages/altair-electron/src/app/menu.js
packages/altair-electron/src/updates.js

Fix error while updating electron.

---

README.md

Removed disabled chrome webstore rating badge

Removed disabled chrome webstore rating badge

---

docs/docs/features/prerequest-scripts.md

corrected typo in docs

---

packages/altair-app/src/app/services/window.service.ts
packages/altair-app/src/app/store/windows/windows.action.ts
packages/altair-app/src/app/store/windows/windows.reducer.ts

Closes #1379.
Set fixedTitle when importing window.

Set fixedTitle when importing window.

---

docs/privacy.md

Added privacy policy

---

packages/altair-app/src/app/directives/theme/theme.directive.ts
packages/altair-app/src/app/services/theme/theme.ts

Merge custom theme to system theme
Closes #1414

Merge custom theme to system theme

---

docs/docs/plugins/writing-plugin.md
packages/altair-app/src/app/services/plugin/context/plugin-context.service.ts
packages/altair-app/src/app/services/theme/theme-registry.service.ts

Added support for theme plugins

---

packages/altair-app/src/app/containers/app/app.component.html
packages/altair-app/src/app/containers/app/app.component.ts
packages/altair-app/src/app/store/settings/settings.reducer.ts

Finally remove plugin system from beta.
Closes #1416

Finally remove plugin system from beta.

---

packages/altair-app/package.json
packages/altair-app/src/app/components/schema-form/schema-form-item-input/schema-form-item-input.component.html
packages/altair-app/src/app/components/schema-form/schema-form-item-input/schema-form-item-input.component.ts
packages/altair-app/src/app/components/schema-form/schema-form-item/schema-form-item.component.html
packages/altair-app/src/app/components/schema-form/schema-form-item/schema-form-item.component.ts
packages/altair-app/src/app/components/schema-form/schema-form/schema-form.component.ts
packages/altair-app/src/app/containers/app/app.component.ts
packages/altair-app/src/app/services/plugin/context/plugin-context.service.spec.ts
packages/altair-app/src/app/services/plugin/context/plugin-context.service.ts
packages/altair-app/src/app/services/plugin/plugin-registry.service.ts
packages/altair-app/src/app/services/theme/theme-registry.service.ts
packages/altair-app/src/app/store/settings/settings.reducer.ts
packages/altair-app/src/app/utils/settings.schema.json
packages/altair-app/src/app/utils/settings_addons.ts
packages/altair-app/src/app/utils/validate_settings_schema.js
packages/altair-app/src/scss/_loading-screen.scss
packages/altair-app/yarn.lock

Updated schema for item input to have autocomplete where available.
Notify user if plugin enables theme

Updated theme type in settings.

---

docs/_config.yml

Updated brew cask command

---

docs/docs/features/graphql-subscriptions.md

There are some typo in the menu in PR #1433 
- [X ] Ran `yarn test-build`
- Fix the typo in the read me file

Fix the typo

---

packages/altair-electron/e2e/index.spec.js
packages/altair-electron/jest.config.e2e.js
packages/altair-electron/package.json
packages/altair-electron/scripts/notarize.js
packages/altair-electron/src/app/index.js
packages/altair-electron/src/app/menu.js
packages/altair-electron/src/app/window.js
packages/altair-electron/src/electron-store-adapter/constants.js
packages/altair-electron/src/electron-store-adapter/electron-store-adapter.js
packages/altair-electron/src/electron-store-adapter/main-store-events.js
packages/altair-electron/src/preload/index.js
packages/altair-electron/yarn.lock

Upgraded electron to v11.

---

packages/altair-app/src/app/modules/altair/store/async-storage-sync.ts

Big schemas (megabytes in SDL) take a few hundred milliseconds to serialize, and doing this on every keystroke is wasteful and causes sluggish performance. By moving it to its own key, the equals-check that is already in place ensures that the schema is only written when it changed.
This change is backwards-compatible as it still reads the schema from the main window key while there is no separate schema key present.
Fixes #1534.
Move the schema to a separate storage key

Move schema to separate storage key

---

packages/altair-app/src/app/modules/altair/components/environment-manager/environment-manager.component.ts
packages/altair-app/src/app/modules/altair/utils/observe-property.ts
packages/altair-app/src/scss/components/_environment-manager.scss

select the currently selected environment when environments change.

---

.github/workflows/pr.yml
packages/altair-app/package.json
packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.ts
packages/altair-app/src/app/modules/altair/components/query-result/query-result.component.ts
packages/altair-app/src/app/modules/altair/config.ts
packages/altair-app/src/app/modules/altair/containers/window/window.component.ts
packages/altair-app/src/app/modules/altair/services/gql/gql.service.ts
packages/altair-app/src/app/modules/altair/store/async-storage-sync.ts
packages/altair-app/src/app/modules/altair/store/query/query.action.ts
packages/altair-app/src/app/modules/altair/store/query/query.interfaces.ts
packages/altair-app/src/app/modules/altair/store/query/query.reducer.ts
packages/altair-app/src/app/modules/altair/store/state.interfaces.ts
packages/altair-static/src/index.ts

Added initialSubscriptionsPayload

---

packages/altair-app/src/app/modules/altair/containers/window/window.component.html
packages/altair-app/src/app/modules/altair/containers/window/window.component.ts
packages/altair-app/src/assets/i18n/default.json
packages/altair-app/src/scss/components/_header.scss

Added forbidden header notice in header dialog

---

.github/PULL_REQUEST_TEMPLATE.md
packages/altair-app/src/app/modules/altair/components/url-box/url-box.component.ts
packages/altair-app/src/app/modules/altair/config.ts
packages/altair-app/src/app/modules/altair/store/query/query.interfaces.ts
packages/altair-app/src/app/modules/altair/store/query/query.reducer.ts
packages/altair-app/src/app/modules/altair/store/reducer-bootstrapper.ts
packages/altair-app/src/app/modules/altair/utils/settings.schema.json
packages/altair-app/src/app/modules/altair/utils/validate_settings_schema.js
packages/altair-static/src/__snapshots__/index.test.ts.snap
packages/altair-static/src/index.test.ts
packages/altair-static/src/index.ts

Added initialHttpMethod config.

---

.github/workflows/pr.yml
packages/altair-app/src/app/modules/altair/containers/window/window.component.html
packages/altair-app/src/app/modules/altair/containers/window/window.component.spec.ts
packages/altair-app/src/app/modules/altair/containers/window/window.component.ts
packages/altair-app/src/app/modules/altair/services/plugin/context/plugin-context.service.spec.ts
packages/altair-app/src/app/modules/altair/services/plugin/context/plugin-context.service.ts
packages/altair-app/src/app/modules/altair/services/subscriptions/subscription-provider-registry.service.ts
site/src/docs/plugins/writing-plugin.md

Added addSubscriptionProvider to plugin context
Closes #1555

Added addSubscriptionProvider to plugin context

---

packages/altair-app/src/app/modules/altair/altair.module.ts
packages/altair-app/src/app/modules/altair/components/query-editor/__snapshots__/query-editor.component.spec.ts.snap
packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.html
packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.spec.ts
packages/altair-app/src/app/modules/altair/components/variable-file-item/variable-file-item.component.spec.ts
packages/altair-app/src/app/modules/altair/components/variable-file-item/variable-file-item.component.ts
packages/altair-app/src/app/modules/altair/containers/window/window.component.ts
packages/altair-app/src/app/modules/altair/effects/local.effect.ts
packages/altair-app/src/app/modules/altair/services/plugin/context/plugin-context.service.spec.ts
packages/altair-app/src/app/modules/altair/services/storage/storage.service.ts
packages/altair-app/src/app/modules/altair/store/reducer-bootstrapper.ts
packages/altair-app/src/app/modules/altair/store/variables/variables.action.ts
packages/altair-app/src/app/modules/altair/store/variables/variables.reducer.ts
packages/altair-app/src/app/modules/altair/store/windows/windows.action.ts
packages/altair-app/src/testing/wrapper/index.ts

persist selected files in storage.

---

packages/altair-app/src/scss/components/_url-box.scss

Resolve #1588
Just a quick fix via dev tools. Check if it works for you too 😉

Set url box send button min width

---

packages/altair-app/src/app/modules/altair/store/async-storage-sync.ts

Fixed bug when changing instanceStorageNamespace

---

packages/altair-app/src/app/modules/altair/components/environment-manager/environment-manager.component.html
packages/altair-app/src/assets/i18n/default.json

Update environment delete button to be more obvious

---

packages/altair-app/src/app/modules/altair/components/schema-form/schema-form-item-input/schema-form-item-input.component.ts
packages/altair-app/src/app/modules/altair/containers/app/app.component.html
packages/altair-app/src/app/modules/altair/containers/app/app.component.ts
packages/altair-app/src/app/modules/altair/directives/theme/theme.directive.ts
packages/altair-app/src/app/modules/altair/services/plugin/context/plugin-context.service.ts
packages/altair-app/src/app/modules/altair/utils/settings.schema.json
packages/altair-app/src/app/modules/altair/utils/validate_settings_schema.js
packages/altair-core/src/plugin/context/context.interface.ts
packages/altair-core/src/theme/defaults/dark.ts
packages/altair-core/src/types/state/settings.interfaces.ts

Added option for also setting dark mode theme

---

packages/altair-app/package.json
packages/altair-app/src/app/modules/altair/altair.module.ts
packages/altair-app/src/app/modules/altair/components/settings-dialog/settings-dialog.component.spec.ts
packages/altair-app/src/app/modules/altair/services/electron-app/electron-app.service.spec.ts
packages/altair-app/src/app/modules/altair/services/keybinder/keybinder.service.spec.ts
packages/altair-app/src/app/modules/altair/services/notify/notify.service.spec.ts
packages/altair-app/src/app/modules/altair/services/notify/notify.service.ts
packages/altair-app/src/app/modules/altair/services/window.service.spec.ts
packages/altair-app/src/scss/components/_alert.scss
packages/altair-app/src/styles.scss
packages/altair-app/yarn.lock

Reintroduced ngx-toastr

---

packages/altair-app/src/app/modules/altair/effects/query.effect.ts
packages/altair-app/src/app/modules/altair/store/query/query.action.ts
packages/altair-app/src/app/modules/altair/store/query/query.reducer.ts
packages/altair-core/src/types/state/query.interfaces.ts

improve subscription client type in query reducer. Catch errors while closing subscription client.
Closes #1649 #1748 #1648

improve subscription client type in query reducer

---

packages/altair-app/src/app/modules/altair/directives/theme/theme.directive.ts

Fix theme changing error

---

packages/altair-app/package.json
packages/altair-app/src/app/modules/altair/containers/app/app.component.ts
packages/altair-app/src/app/modules/altair/pipes/keys/keys.pipe.ts
packages/altair-app/src/app/modules/altair/services/window.service.ts
packages/altair-app/src/app/modules/altair/utils/curl.ts
packages/altair-app/src/app/modules/altair/utils/index.ts
packages/altair-core/src/config.ts
packages/altair-core/src/types/state/window.interfaces.ts
packages/altair-express-middleware/example/index.ts
packages/altair-static/src/index.test.ts
packages/altair-static/src/index.ts

added support for providing multiple windows when initializing altair
Closes #1756

added support for providing multiple windows when initializing altair

---

packages/altair-electron/package.json
packages/altair-electron/yarn.lock

updated electron-updater

---

packages/altair-app/src/app/modules/altair/effects/query.effect.ts

use transformed data environment in subscription connection params hydration
Closes #1764

use transformed data environment in subscription connection params hydration

---

packages/altair-app/fixtures/test.sdl
packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-utils.ts
packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer/doc-viewer.component.ts
packages/altair-app/src/app/modules/altair/services/gql/__snapshots__/generateQuery.spec.ts.snap
packages/altair-app/src/app/modules/altair/services/gql/fillFields.ts
packages/altair-app/src/app/modules/altair/services/gql/generateQuery.spec.ts
packages/altair-app/src/app/modules/altair/services/gql/generateQuery.ts
packages/altair-app/src/app/modules/altair/services/gql/gql.service.ts
packages/altair-app/src/app/modules/altair/services/gql/prettifier.ts
packages/altair-app/src/environments/environment.prod.ts
packages/altair-app/src/environments/environment.ts
packages/altair-app/tsconfig.json

added new logic for generating queries and fragments.

---

packages/altair-app/package.json
packages/altair-app/src/app/modules/altair/components/add-collection-query-dialog/add-collection-query-dialog.component.html
packages/altair-app/src/app/modules/altair/components/add-collection-query-dialog/add-collection-query-dialog.component.spec.ts
packages/altair-app/src/app/modules/altair/components/add-collection-query-dialog/add-collection-query-dialog.component.ts
packages/altair-app/src/app/modules/altair/components/query-collection-item/query-collection-item.component.html
packages/altair-app/src/app/modules/altair/components/query-collection-item/query-collection-item.component.spec.ts
packages/altair-app/src/app/modules/altair/components/query-collection-item/query-collection-item.component.ts
packages/altair-app/src/app/modules/altair/components/query-collections/query-collections.component.html
packages/altair-app/src/app/modules/altair/components/query-collections/query-collections.component.spec.ts
packages/altair-app/src/app/modules/altair/components/query-collections/query-collections.component.ts
packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.ts
packages/altair-app/src/app/modules/altair/containers/window/window.component.ts
packages/altair-app/src/app/modules/altair/effects/query-collection.effect.ts
packages/altair-app/src/app/modules/altair/effects/query.effect.ts
packages/altair-app/src/app/modules/altair/modules/shared/shared.module.ts
packages/altair-app/src/app/modules/altair/services/gql/gql.service.spec.ts
packages/altair-app/src/app/modules/altair/services/gql/gql.service.ts
packages/altair-app/src/app/modules/altair/services/query-collection/query-collection.service.spec.ts
packages/altair-app/src/app/modules/altair/services/query-collection/query-collection.service.ts
packages/altair-app/src/app/modules/altair/services/storage/storage.service.ts
packages/altair-app/src/app/modules/altair/store/collection/collection.action.ts
packages/altair-app/src/scss/_ant-overrides.scss
packages/altair-app/src/setup-jest.ts
packages/altair-app/src/testing/utils.ts
packages/altair-app/src/testing/wrapper/index.ts
packages/altair-app/yarn.lock
packages/altair-core/src/types/state/collection.interfaces.ts

added query subcollections logic.

---

packages/altair-app/src/app/modules/altair/altair.module.ts
packages/altair-app/src/app/modules/altair/components/add-collection-query-dialog/add-collection-query-dialog.component.ts
packages/altair-app/src/app/modules/altair/components/dialog/dialog.component.ts
packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-utils.ts
packages/altair-app/src/app/modules/altair/components/header/header.component.ts
packages/altair-app/src/app/modules/altair/components/plugin-manager/plugin-manager.component.ts
packages/altair-app/src/app/modules/altair/components/post-request-editor/post-request-editor.component.ts
packages/altair-app/src/app/modules/altair/components/pre-request-editor/pre-request-editor.component.ts
packages/altair-app/src/app/modules/altair/components/query-collection-item/query-collection-item.component.ts
packages/altair-app/src/app/modules/altair/components/query-result/query-result.component.ts
packages/altair-app/src/app/modules/altair/components/variable-file-item/variable-file-item.component.ts
packages/altair-app/src/app/modules/altair/components/window-switcher/window-switcher.component.ts
packages/altair-app/src/app/modules/altair/containers/window/window.component.ts
packages/altair-app/src/app/modules/altair/effects/query-collection.effect.ts
packages/altair-app/src/app/modules/altair/effects/query.effect.ts
packages/altair-app/src/app/modules/altair/error-handler.ts
packages/altair-app/src/app/modules/altair/interfaces/shared.ts
packages/altair-app/src/app/modules/altair/services/electron-app/electron-app.service.ts
packages/altair-app/src/app/modules/altair/store/collection/collection.action.ts
packages/altair-app/src/app/modules/altair/utils/issue/index.ts
packages/altair-app/src/app/modules/altair/utils/issue/template.ts
packages/altair-app/src/app/modules/altair/utils/settings_addons.ts
packages/altair-static/src/index.ts

cleanup anys

---

packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.html
packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.ts
packages/altair-app/src/app/modules/altair/components/settings-dialog/settings-dialog.component.ts
packages/altair-app/src/app/modules/altair/components/variables-editor/variables-editor.component.ts
packages/altair-app/src/app/modules/altair/effects/query-collection.effect.ts
packages/altair-app/src/app/modules/altair/services/keybinder/keybinder.service.ts
packages/altair-app/src/scss/_ant-overrides.scss

Resolving issues

---

.github/workflows/pr.yml
nx.json
package.json
packages/altair-core/src/subscriptions/providers/graphql-ws.ts
packages/altair-core/src/subscriptions/providers/ws.ts
packages/altair-electron/package.json
site/package.json
site/src/docs/features/variables.md
yarn.lock

Added nx to workspace

---

README.md

Fix broken config options link in README

Fix broken config options link in README

---

.github/workflows/pr-post.yml
.github/workflows/pr.yml
packages/altair-electron/package.json

test electron builds

---

packages/altair-app/jest.config.js
packages/altair-app/package.json
packages/altair-app/src/app/modules/altair/components/query-editor/__snapshots__/query-editor.component.spec.ts.snap
packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.html
packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.ts
packages/altair-app/src/app/modules/altair/modules/shared/shared.module.ts
packages/altair-app/src/scss/components/_editor.scss
yarn.lock

Closes #1933
Closes #1707
Closes #1942

Added functionality to resize variable window

---

.github/workflows/pr-post.yml
firebase.json
firestore.rules
functions/.eslintrc.js
functions/.gitignore
functions/jest.config.js
functions/package.json
functions/tests/rules.spec.ts
functions/tsconfig.dev.json
functions/tsconfig.json
libs/prettier-config/index.js
libs/prettier-config/package.json
package.json
packages/altair-app/.prettierrc
packages/altair-app/package.json
packages/altair-app/src/app/modules/altair/components/variables-editor/__snapshots__/variables-editor.component.spec.ts.snap
packages/altair-app/src/app/modules/altair/containers/altair/altair.component.html
packages/altair-app/src/app/modules/altair/effects/query-collection.effect.ts
packages/altair-app/src/app/modules/altair/services/query-collection/query-collection.service.spec.ts
packages/altair-app/src/app/modules/altair/services/query-collection/query-collection.service.ts
packages/altair-app/src/app/modules/altair/services/storage/storage.service.ts
packages/altair-app/src/environments/environment.ts
yarn.lock

disable post pr workflow
added action logs for query collection

few updates

---

packages/altair-app/src/app/modules/altair/components/beta-indicator/beta-indicator.component.html
packages/altair-app/src/app/modules/altair/components/beta-indicator/beta-indicator.component.spec.ts
packages/altair-app/src/app/modules/altair/components/beta-indicator/beta-indicator.component.ts
packages/altair-app/src/app/modules/altair/components/components.module.ts
packages/altair-app/src/app/modules/altair/components/query-editor/__snapshots__/query-editor.component.spec.ts.snap
packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.html
packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.spec.ts
packages/altair-app/src/app/modules/altair/components/query-editor/query-editor.component.ts
packages/altair-app/src/app/modules/altair/containers/window/window.component.html
packages/altair-app/src/app/modules/altair/containers/window/window.component.ts
packages/altair-app/src/app/modules/altair/directives/theme/theme.directive.ts
packages/altair-app/src/app/modules/altair/modules/shared/shared.module.ts
packages/altair-app/src/app/modules/altair/store/settings/settings.action.ts
packages/altair-app/src/app/modules/altair/store/settings/settings.reducer.ts
packages/altair-app/src/app/modules/altair/utils/settings.schema.json
packages/altair-app/src/app/modules/altair/utils/validate_settings_schema.js
packages/altair-app/src/scss/_all.scss
packages/altair-app/src/scss/_ant-overrides.scss
packages/altair-app/src/scss/components/_beta-indicator.scss
packages/altair-app/src/testing/wrapper/index.ts
packages/altair-core/.prettierrc
packages/altair-core/src/types/state/settings.interfaces.ts

added beta indicator. Used for new editor

added beta indicator.

---

packages/altair-app/src/app/modules/altair/effects/query-collection.effect.ts
packages/altair-app/src/app/modules/altair/services/query-collection/query-collection.service.spec.ts
packages/altair-app/src/app/modules/altair/services/query-collection/query-collection.service.ts

fixed importing nested collection

---

DEV.md
site/src/docs/README.md
site/src/docs/features/editor-capabilities.md
site/src/docs/features/settings-pane.md

Correct small typos and add missing words.

Improve docs

---

.github/workflows/firebase-deploy.yml
firestore.indexes.json
functions/package.json
functions/scripts/prepare.sh
package.json

replaced w9jds/firebase-action with custom logic

---

.eslintignore
.github/workflows/pr.yml
packages/altair-dashboard/next.config.js
packages/altair-dashboard/package.json

added job to deploy dashboard

---

.github/workflows/pr-e2e.yml
package.json
packages/altair-app/package.json
packages/altair-app/src/app/modules/altair/services/account/account.service.ts
packages/altair-app/src/app/modules/altair/services/api/api.service.ts
packages/altair-app/src/app/modules/altair/services/firebase/firebase.ts
packages/altair-app/src/environments/environment.prod.ts
packages/altair-app/src/environments/environment.ts
packages/altair-dashboard/lib/useUser.ts
packages/altair-dashboard/package.json
packages/altair-dashboard/pages/teams/[id].tsx
packages/altair-dashboard/pages/teams/index.tsx
packages/altair-electron/package.json
packages/altair-electron/src/auth/server/index.ts
packages/altair-static/package.json
packages/altair-static/scripts/prepare_dist.js
packages/electron-auth-client/package.json
packages/firebase-functions/package.json
packages/firebase-functions/src/counters.ts
packages/firebase-functions/src/onCreateTrigger.ts
packages/firebase-functions/src/onDeleteTrigger.ts
packages/firebase-functions/tests/rules.spec.ts
packages/firebase-utils/package.json
site/package.json
yarn.lock

used private @altairgraphql/ scope for private packages

---

packages/altair-app/src/app/modules/altair/components/account-dialog/account-dialog.component.html
site/src/.vuepress/theme/components/Contributions.vue

added newsletter subscribe button

---

packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-type/doc-viewer-type.component.ts

Handle input types in doc viewer

---

packages/altair-app/src/app/modules/altair/utils/index.ts

Reverted the changes which possibly has caused error.

Reverted the changes which possibly has caused error #2111

---

packages/altair-api-utils/src/query.ts
packages/altair-api/src/app.controller.ts
packages/altair-api/src/newrelic/newrelic.interceptor.ts
packages/altair-api/src/query-collections/query-collections.controller.spec.ts
packages/altair-api/src/query-collections/query-collections.module.ts
packages/altair-api/src/query-collections/query-collections.service.spec.ts
packages/altair-api/src/query-collections/query-collections.service.ts
packages/altair-api/src/teams/teams.service.ts
packages/altair-app/package.json
packages/altair-app/src/app/modules/altair/services/api/api.service.ts
packages/altair-db/package.json
packages/altair-db/prisma/migrations/20230216011836_add_team_workspace_support/migration.sql
packages/altair-db/prisma/schema.prisma
packages/altair-db/src/seed.ts

Add team collection support in API

---

packages/altair-api/src/app.controller.spec.ts
packages/altair-api/src/app.controller.ts
packages/altair-api/src/app.module.ts
packages/altair-api/src/main.ts
packages/altair-api/src/queries/queries.service.ts
packages/altair-api/src/query-collections/query-collections.service.ts

Updated query collection sharing functionality

---

packages/altair-api/src/auth/user/user.service.ts

added getStripeCustomerId

---

packages/altair-app/src/app/modules/altair/services/gql/generateQuery.ts

added support for interface types in generateQuery

---

packages/altair-app/src/app/modules/altair/utils/headers.ts
packages/altair-core/src/subscriptions/providers/graphql-sse.ts

Fix headerListToMap transformation error

---

packages/altair-app/src/app/modules/altair/effects/query.effect.ts
packages/altair-app/src/app/modules/altair/services/gql/gql.service.ts

Move setting electron header to gql service

---

packages/altair-app/src/app/modules/altair/components/account-dialog/account-dialog.component.html
packages/altair-app/src/app/modules/altair/services/window.service.ts
packages/altair-app/src/assets/i18n/en-US.json

fix update loop

---

packages/altair-api-utils/src/client.ts
packages/altair-api-utils/src/user.ts
packages/altair-api/src/auth/auth.module.ts
packages/altair-api/src/auth/user/user.controller.ts
packages/altair-api/src/queries/queries.service.ts
packages/altair-api/src/query-collections/query-collections.service.ts
packages/altair-api/src/teams/teams.service.ts
packages/altair-api/test/providers.ts
packages/altair-app/src/app/modules/altair/components/account-dialog/__snapshots__/account-dialog.component.spec.ts.snap
packages/altair-app/src/app/modules/altair/components/account-dialog/account-dialog.component.html
packages/altair-app/src/app/modules/altair/components/dialog/dialog.component.html
packages/altair-app/src/app/modules/altair/effects/account.effect.ts
packages/altair-app/src/app/modules/altair/modules/shared/shared.module.ts
packages/altair-app/src/app/modules/altair/store/account/account.action.ts
packages/altair-app/src/app/modules/altair/store/account/account.reducer.ts
packages/altair-app/src/assets/i18n/default.json
packages/altair-app/src/scss/_links.scss
packages/altair-app/src/scss/components/_account-dialog.scss
packages/altair-app/src/scss/components/_dialog.scss
packages/altair-core/src/types/state/account.interfaces.ts
packages/altair-dashboard/components/Navbar.tsx
packages/altair-dashboard/pages/index.tsx

updated account dialog

---

packages/altair-app/src/app/modules/altair/services/gql/gql.service.ts
yarn.lock

fix headers not getting set in electron apps

---

packages/altair-api-utils/src/client.ts
packages/altair-api-utils/src/user.ts
packages/altair-api/src/auth/user/user.controller.ts
packages/altair-api/src/main.ts
packages/altair-api/src/queries/dto/create-query.dto.ts
packages/altair-api/src/query-collections/dto/create-query-collection.dto.ts
packages/altair-app/src/app/modules/altair/components/account-dialog/account-dialog.component.html
packages/altair-app/src/app/modules/altair/effects/account.effect.ts
packages/altair-app/src/app/modules/altair/effects/query-collection.effect.ts
packages/altair-app/src/app/modules/altair/services/account/account.service.ts
packages/altair-app/src/app/modules/altair/services/notify/notify.service.ts
packages/altair-app/src/app/modules/altair/store/account/account.action.ts
packages/altair-app/src/app/modules/altair/store/account/account.reducer.ts
packages/altair-app/src/app/modules/altair/utils/index.ts
packages/altair-app/src/scss/components/_account-dialog.scss
packages/altair-app/src/scss/components/_tooltip.scss
packages/altair-core/src/types/state/account.interfaces.ts

Fixes uncaught error when syncing collection to remote
Fixes #2164 
Fixes #2163

Added user plan and stats in the app

---

packages/altair-app/src/app/modules/altair/containers/altair/altair.component.ts
packages/altair-core/src/config.ts
packages/altair-static/src/index.ts

Added init option to disable account feature

---

packages/altair-app/src/app/modules/altair/components/account-dialog/account-dialog.component.html
packages/altair-app/src/app/modules/altair/components/account-dialog/account-dialog.component.ts
packages/altair-app/src/app/modules/altair/containers/altair/altair.component.html
packages/altair-app/src/assets/i18n/default.json

Added account dialog in logged in state billing page link

---

packages/altair-api/src/auth/user/user.service.ts
packages/altair-api/src/team-memberships/team-memberships.service.ts
packages/altair-api/test/app.e2e-spec.ts
packages/altair-api/test/auth.e2e-spec.ts
packages/altair-api/test/e2e-test-utils.ts
packages/altair-api/test/queries.e2e-spec.ts
packages/altair-api/test/query-collections.e2e-spec.ts
packages/altair-api/test/team-memberships.e2e-spec.ts
packages/altair-api/test/teams.e2e-spec.ts
packages/altair-api/test/users.e2e-spec.ts
packages/altair-api/test/workspaces.e2e-spec.ts
packages/altair-db/prisma/schema.prisma

add more integration tests

---

packages/altair-app/src/app/modules/altair/effects/query.effect.ts
yarn.lock

fix issue with multiple synchronous actions

---

packages/altair-app/src/app/modules/altair/components/settings-dialog/extensions.ts
packages/altair-app/src/app/modules/altair/components/settings-dialog/json-completion.ts

Added JSONCompletion class for codemirror

---

packages/altair-api/src/team-memberships/team-memberships.service.ts

Only consider unique members for the subscription

---

packages/altair-app/src/app/modules/altair/components/post-request-editor/__snapshots__/post-request-editor.component.spec.ts.snap
packages/altair-app/src/app/modules/altair/components/post-request-editor/post-request-editor.component.html
packages/altair-app/src/app/modules/altair/components/post-request-editor/post-request-editor.component.ts
packages/altair-app/src/app/modules/altair/components/pre-request-editor/__snapshots__/pre-request-editor.component.spec.ts.snap
packages/altair-app/src/app/modules/altair/components/pre-request-editor/pre-request-editor.component.html
packages/altair-app/src/app/modules/altair/components/pre-request-editor/pre-request-editor.component.ts
packages/altair-app/src/app/modules/altair/effects/query.effect.ts
packages/altair-app/src/app/modules/altair/services/db.service.ts
packages/altair-app/src/app/modules/altair/services/pre-request/evaluator-worker.factory.ts
packages/altair-app/src/app/modules/altair/services/pre-request/evaluator.ts
packages/altair-app/src/app/modules/altair/services/pre-request/evaluator.worker.ts
packages/altair-app/src/app/modules/altair/services/pre-request/events.ts
packages/altair-app/src/app/modules/altair/services/pre-request/helpers.ts
packages/altair-app/src/app/modules/altair/services/pre-request/pre-request.service.spec.ts
packages/altair-app/src/app/modules/altair/services/pre-request/pre-request.service.ts
packages/altair-app/src/app/modules/altair/services/query/query.service.ts
packages/altair-app/src/app/modules/altair/utils/settings.schema.json
packages/altair-app/src/app/modules/altair/utils/validate_settings_schema.js
packages/altair-app/src/scss/components/_request-script-editor.scss
packages/altair-app/src/setup-jest.ts
packages/altair-app/tsconfig.worker.json
packages/altair-core/src/types/state/settings.interfaces.ts
site/src/docs/features/prerequest-scripts.md

wip: worker based script

---

packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-search-results/doc-viewer-search-results.component.html
packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer/doc-viewer.component.html
packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer/doc-viewer.component.ts
packages/altair-app/src/app/modules/altair/effects/query.effect.ts

doc improvements

---

packages/altair-app/src/app/modules/altair/components/url-box/url-box.component.ts
packages/altair-app/src/app/modules/altair/components/x-input/x-input.component.ts
packages/altair-app/src/app/modules/altair/services/pre-request/evaluator.ts

url box improvements

---

packages/altair-electron/src/app/window.ts

only apply the CSP to the frames and not the scripts in desktop apps

---

packages/altair-app/src/app/modules/altair/components/url-box/url-box.component.spec.ts
packages/altair-app/src/app/modules/altair/components/url-box/url-box.component.ts
packages/altair-app/src/app/modules/altair/services/pre-request/evaluator.ts
packages/altair-app/src/app/modules/altair/services/pre-request/evaluator.worker.ts
packages/altair-app/src/app/modules/altair/services/pre-request/events.ts
packages/altair-app/src/app/modules/altair/services/pre-request/pre-request.service.ts
site/src/docs/features/settings-pane.md

Closes #2259 
Also handles updating active environment from new request script engine. Closes #2258

fix issue with http protocol append to url with variable

---

package.json
packages/altair-app/package.json
packages/altair-electron-interop/package.json
packages/altair-electron/electron-builder.yml
packages/altair-electron/package.json
packages/altair-electron/src/app/index.ts
packages/altair-electron/src/app/window.ts
packages/altair-electron/src/utils/log.ts
yarn.lock

update electron to v26

---

packages/altair-api/package.json
yarn.lock

updated stripe

---

packages/altair-koa-middleware/package.json
yarn.lock

Move koa dependencies as peerDependencies

---

bin/dev.sh
packages/altair-api/package.json
packages/altair-app/package.json
packages/altair-core/package.json
packages/altair-electron/package.json
yarn.lock

updated uuid

---

.github/workflows/pr.yml
yarn.lock

updated deps

---

README.md

Updated few  broken links to the correct official altair-graphql documentaion links

Updated broken links in readme.md

---

.github/workflows/pr-e2e.yml
.github/workflows/pr.yml
.github/workflows/release.yml
packages/altair-app/angular.json
packages/altair-app/tsconfig.json
packages/altair-electron/.gitignore
packages/altair-electron/package.json
packages/altair-electron/tsconfig.json
yarn.lock

sourcemap upload to sentry

---

.github/workflows/release.yml
packages/altair-app/src/app/modules/altair/services/electron-app/electron-app.service.ts
packages/altair-electron/src/app/window.ts
packages/altair-electron/src/index.ts
packages/altair-electron/tsconfig.json

specify sentry release identifier

---

.github/workflows/pr.yml
.github/workflows/release.yml

separate sentry releases

---

packages/altair-app/package.json
packages/altair-electron-interop/package.json
packages/altair-electron/package.json
packages/altair-electron/src/app/actions.ts
packages/altair-electron/src/app/index.ts
packages/altair-electron/src/app/window.ts
yarn.lock

fix errors recreating electron window

---

packages/altair-api-utils/src/query.ts
packages/altair-api/src/query-collections/dto/create-query-collection.dto.ts
packages/altair-api/src/query-collections/query-collections.service.ts
packages/altair-app/src/app/modules/altair/services/api/api.service.ts
packages/altair-app/src/app/modules/altair/store/async-storage-sync.ts
packages/altair-electron/src/updates.ts

pass extra collection fields to remote

---

packages/altair-app/src/app/modules/altair/components/environment-manager/environment-manager.component.ts

lint json in environment manager

---

packages/altair-api/package.json
packages/altair-app/src/app/modules/altair/services/query/query.service.ts

Consider all collections when running transform scripts

---

packages/altair-koa-middleware/package.json

Moved koa-send to dependencies

---

packages/altair-app/src/app/modules/altair/components/variables-editor/utils.ts

handle null variableToType objects

---

packages/altair-app/src/app/modules/altair/components/schema-form/schema-form-item-input/schema-form-item-input.component.ts
packages/altair-app/src/app/modules/altair/components/schema-form/schema-form-item-list/schema-form-item-list.component.ts
packages/altair-app/src/app/modules/altair/components/schema-form/schema-form-item/schema-form-item.component.html
packages/altair-app/src/app/modules/altair/components/schema-form/schema-form-item/schema-form-item.component.ts
site/src/.vuepress/theme/components/Contributions.vue
yarn.lock

Fixed missing schema form input for lists and strings

---

packages/altair-api-utils/package.json
packages/altair-api-utils/scripts/build.cjs
packages/altair-api-utils/scripts/build.sh
packages/altair-api-utils/src/config.ts
packages/altair-app/src/environments/environment.prod.ts
packages/altair-app/src/environments/environment.ts

Make API client options configurable

---

packages/altair-app/src/app/modules/altair/components/url-box/__snapshots__/url-box.component.spec.ts.snap
packages/altair-app/src/app/modules/altair/components/url-box/url-box.component.html
packages/altair-app/src/app/modules/altair/components/url-box/url-box.component.ts
packages/altair-app/src/app/modules/altair/effects/query.effect.ts
packages/altair-app/src/app/modules/altair/services/gql/gql.service.ts
packages/altair-app/src/assets/i18n/default.json

added request batching functionality

---

packages/altair-app/src/app/modules/altair/services/pre-request/cors-worker.ts
packages/altair-app/src/app/modules/altair/services/pre-request/evaluator-worker.factory.ts
packages/altair-app/src/app/modules/altair/services/pre-request/evaluator.ts

Handle cross origin worker

---

packages/altair-docs/.vitepress/plugins/github-metadata.data.ts
packages/altair-docs/.vitepress/theme/components/Downloads.vue
packages/altair-electron-interop/src/index.ts
packages/altair-electron-interop/src/settings.ts
packages/altair-electron-interop/tsconfig.json
packages/altair-electron-settings/index.html
packages/altair-electron-settings/package.json
packages/altair-electron-settings/postcss.config.js
packages/altair-electron-settings/src/App.tsx
packages/altair-electron-settings/src/NetworkSettings.tsx
packages/altair-electron-settings/src/index.css
packages/altair-electron-settings/src/main.tsx
packages/altair-electron-settings/tailwind.config.js
packages/altair-electron-settings/tsconfig.json
packages/altair-electron-settings/tsconfig.node.json
packages/altair-electron-settings/vite.config.ts
packages/altair-electron/package.json
packages/altair-electron/src/app/actions.ts
packages/altair-electron/src/settings/constants.ts
packages/altair-electron/src/settings/main/events.ts
packages/altair-electron/src/settings/main/store.ts
yarn.lock

Created electron-settings package

---

packages/altair-docs/.vitepress/plugins/github-metadata.data.ts
packages/altair-docs/.vitepress/theme/components/Downloads.vue
packages/altair-electron-interop/src/index.ts
packages/altair-electron-interop/src/settings.ts
packages/altair-electron-interop/tsconfig.json
packages/altair-electron-settings/index.html
packages/altair-electron-settings/package.json
packages/altair-electron-settings/postcss.config.js
packages/altair-electron-settings/src/App.tsx
packages/altair-electron-settings/src/NetworkSettings.tsx
packages/altair-electron-settings/src/index.css
packages/altair-electron-settings/src/main.tsx
packages/altair-electron-settings/tailwind.config.js
packages/altair-electron-settings/tsconfig.json
packages/altair-electron-settings/tsconfig.node.json
packages/altair-electron-settings/vite.config.ts
packages/altair-electron/package.json
packages/altair-electron/src/app/actions.ts
packages/altair-electron/src/auth/server/index.ts
packages/altair-electron/src/settings/constants.ts
packages/altair-electron/src/settings/main/events.ts
packages/altair-electron/src/settings/main/store.ts
yarn.lock

fix electron user login

---

.prettierrc
packages/altair-app/.eslintrc.js
packages/altair-app/src/app/modules/altair/containers/window/window.component.html
packages/altair-app/src/assets/i18n/default.json
packages/altair-app/src/scss/components/_dialog.scss
packages/altair-docs/docs/learn/web-limitations.md

added info about global headers

---

packages/altair-core/src/authorization/providers/api-key.spec.ts
packages/altair-core/src/authorization/providers/api-key.ts
packages/altair-core/src/authorization/providers/basic.spec.ts
packages/altair-core/src/authorization/providers/basic.ts
packages/altair-core/src/authorization/providers/bearer.spec.ts
packages/altair-core/src/authorization/providers/bearer.ts

hydrate auth fields

---

packages/altair-app/src/index.html
packages/altair-docs/docs/features/multiple-platforms.md
packages/altair-docs/docs/index.md
packages/altair-docs/index.md
packages/login-redirect/src/script.ts

updated web app domain

---

packages/altair-app/src/app/modules/altair/services/pre-request/helpers.ts
packages/altair-app/src/app/modules/altair/services/query/query.service.ts

fix issue with empty env when using auth

---

packages/altair-app/src/app/modules/altair/components/post-request-editor/post-request-editor.component.ts
packages/altair-app/src/app/modules/altair/components/pre-request-editor/pre-request-editor.component.ts
packages/altair-app/src/app/modules/altair/effects/query.effect.ts
packages/altair-app/src/app/modules/altair/services/gql/gql.service.spec.ts
packages/altair-app/src/app/modules/altair/services/gql/gql.service.ts
packages/altair-app/src/app/modules/altair/services/pre-request/pre-request.service.spec.ts
packages/altair-app/src/app/modules/altair/services/query/query.service.ts
packages/altair-core/src/script/types.ts
packages/altair-core/src/types/state/query.interfaces.ts

added logic for GraphQL request extensions

---

packages/altair-app/src/app/modules/altair/services/query/query.service.spec.ts
packages/altair-app/src/app/modules/altair/services/query/query.service.ts

fix missing auth headers

---

packages/altair-app/src/app/modules/altair/services/window.service.ts
packages/altair-static/src/__snapshots__/index.test.ts.snap
packages/altair-static/src/index.test.ts
packages/altair-static/src/index.ts

fix incorrect initialQuery transform by replace

---

packages/altair-electron/src/app/window.ts

only set CSP to altair protocol

---

packages/altair-app/src/app/modules/altair/services/gql/gql.service.spec.ts
packages/altair-app/src/app/modules/altair/services/gql/gql.service.ts
packages/altair-core/src/request/__snapshots__/response-builder.spec.ts.snap
packages/altair-core/src/request/handlers/http.spec.ts
packages/altair-core/src/request/handlers/http.ts
packages/altair-core/src/request/response-builder.spec.ts
packages/altair-core/src/request/response-builder.ts

fix a bunch of things in 7.2.0

---

packages/altair-app/src/app/modules/altair/components/add-collection-query-dialog/add-collection-query-dialog.component.spec.ts
packages/altair-app/src/app/modules/altair/components/add-collection-query-dialog/add-collection-query-dialog.component.ts
packages/altair-app/src/app/modules/altair/services/query-collection/query-collection.service.ts

fix missing collection

---

bin/dev.sh
package.json
packages/altair-app/angular.json
packages/altair-app/package.json
packages/altair-app/src/app/modules/altair/containers/altair/altair.component.html
packages/altair-app/src/app/modules/altair/services/plugin/plugin-registry.service.ts
packages/altair-app/src/app/modules/altair/services/pre-request/evaluator-client.factory.ts
packages/altair-app/src/scss/components/_alert.scss
packages/altair-core/src/script/evaluator-client-engine.ts
packages/altair-core/src/script/types.ts
packages/altair-docs/docs/learn/mv3.md

mv3 migration related UX changes

---

packages/altair-app/src/app/modules/altair/effects/query.effect.ts
packages/altair-app/src/app/modules/altair/store/gql-schema/gql-schema.action.ts

start loading before transform scripts

---

bin/update_version.sh
packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-deprecated/doc-viewer-deprecated.component.html
packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-deprecated/doc-viewer-deprecated.component.ts
packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-field/doc-viewer-field.component.html
packages/altair-app/src/app/modules/altair/components/doc-viewer/doc-viewer-type/doc-viewer-type.component.html
packages/altair-app/src/app/modules/altair/effects/query.effect.ts
packages/altair-app/src/app/modules/altair/services/gql/gql.service.ts
packages/altair-app/src/scss/components/_doc-viewer.scss
packages/altair-core/src/types/state/settings.interfaces.ts
test-server/src/schema/index.ts

added options for introspection querying + deprecation UX

---

.github/workflows/pr-master-tag.yml

also run PR+master actions for tags

---

packages/altair-app/src/app/modules/altair/services/window.service.ts

fix issue with saving query to collection

---

packages/altair-app/src/app/modules/altair/services/plugin/context/plugin-context.service.ts
packages/altair-app/src/app/modules/altair/services/plugin/plugin-registry.service.ts
packages/altair-core/src/plugin/v3/frame-worker.ts
packages/altair-core/src/plugin/v3/manifest.ts
packages/altair-core/src/plugin/v3/parent-worker.ts
packages/altair-core/src/utils/inject.ts
packages/altair-docs/docs/plugins/writing-plugin.md
packages/altair-iframe-sandbox/src/main.ts
packages/altair-iframe-sandbox/src/plugin-sandbox.ts

implement js entry in plugin v3

---

packages/login-redirect/package.json
packages/login-redirect/src/login-redirect.ts

fixed login-redirect build

---

packages/altair-app/src/app/modules/altair/components/account-dialog/__snapshots__/account-dialog.component.spec.ts.snap
packages/altair-app/src/scss/_codemirror6.scss

set z-index on cm-panels

---

packages/altair-app/src/app/modules/altair/components/request-handler-dialog/request-handler-dialog.component.ts
packages/altair-app/src/app/modules/altair/store/query/query.reducer.ts
packages/altair-app/src/polyfills.ts

refactored request handler state handling

---

.github/workflows/_publish-electron.yml
.github/workflows/_tests.yml
packages/altair-app/src/app/modules/altair/components/environment-manager/environment-manager.component.spec.ts
packages/altair-app/src/app/modules/altair/components/environment-manager/environment-manager.component.ts

Validate environment variable keys are valid

---

packages/altair-app/src/app/modules/altair/utils/url.ts

only update URL if there is a consumed value

---

packages/altair-api-utils/src/client.ts
packages/altair-app/src/app/modules/altair/containers/altair/altair.component.ts
packages/altair-app/src/app/modules/altair/services/sharing/sharing.service.ts
packages/altair-app/src/app/modules/altair/utils/url.ts
packages/altair-docs/docs/features/multiple-windows.md

Open new window with deep linking
